### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by moubry** [nikhaldi/exception_notification-rake#19]
Currently, this gem only supports Rails `~> 4.1.0` and it would be great if it worked with Rails 5 as well.

**Comment by nikhaldi** [comment]
Thanks for the pointers. I definitely want to support Rails 5, it's just a matter of finding some time to sit down and do it. In the meantime, I would gladly accept pull requests for this!

**Comment by nikhaldi** [comment]
I just published a new version of the gem (0.3.0.rc1) which supports Rails 4.2 and later, including Rails 5. It needs a bit more testing before I make it final (removing the .rc1). If you have time to try it out and let me know how it goes, that would help a lot. Thanks!
